### PR TITLE
ADD - Height properties to Steps Widget and allow to scroll inside (f…

### PR DESCRIPTION
**Pull request by cronux35**
Steps widget : height property added in order to permit scroll in the dashboard.
CSS : add a display: none webkit to css in order to hide scrollbars without removing scroll functions (maximize onscreen place for small screen setup).

### CODE REVIEW

**Comment by avollkopf** [comment]
@cronux35 can you rebase your PR an the base of my development branch? Merging this PR cannot be done easily.

**Comment by cronux35** [comment]
Hello Alexander,
Don’t really understand what you ask me, I’m not familiar with git. Can you guide me a little bit to do that ?

**Comment by avollkopf** [comment]
I will be travelling the next two weeks... Let's work it out when I am back

**Comment by phylax2020** [comment]
Hallo François,
your change in app.css removes also horizontal scrollbars, especially in dashboard. So it is not possible to bring the complete dashboard into view. This may work on smartphones or tablets using swipe gestures but not on desktop computers or notebooks without touchscreens. Attached an example of my dashboard with reduced window size on my desktop computer:

missing_scroll_bars

**Comment by cronux35** [comment]
Thanks for the information, I’m effectively using a touchscreen and I didn’t think it will block desktop app if dashboard is too big for the screen. I will try to add a global settings for touchscreen and enable that settings only if activate. I’ll try that asap.

**Comment by avollkopf** [comment]
Is there still activity on this PR? It is also not mergeable with the latest versions. If there is currently no activity, I will close it and in case of new activity, a new PR should be opened which is based on the latest version.

**Pull request closed without merging**
